name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Windows executable
        run: go build -o obs-timecode-server.exe .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            obs-timecode-server.exe
            obs-timecode-generator.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
